

class P2:
    """
    Even Fibonacci numbers

    Problem 2
    Each new term in the Fibonacci sequence is generated by adding
    the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values
    do not exceed four million, find the sum of the even-valued terms.
    """
    def __init__(self, num: int = 4000000):
        self.description = 'Even Fibonacci numbers'
        self.result = self.calc(num=num)

    def calc(self, num):
        fibs = []
        ncalc = 0
        a = 0
        b = 1
        while ncalc <= num:
            ncalc = a + b
            a = b
            b = ncalc
            fibs.append(ncalc)

        result = 0
        for fib in fibs:
            if fib % 2 == 0:
                result = result + fib

        return result
